### ISSUE TITLE
Possible build issue w/ macOS 10.11

### ISSUE THREAD

**Issue by jadudm** [adafruit/mu#1]
The honor of the first issue...

I have downloaded and tested the current Adafruit Mu build on my laptop, which is running 10.13.1. This, naturally, meant it was ready to deploy to 34 students without further testing. Fortunately, I like working on the bleeding edge, and committed to the CPx for this term; there's no comment there, other than "I'm happy to be in the vanguard for live bug-finding."

A student running 10.11.6 received the following error:

```
Last login: Thu Jan 25 11:26:58 on ttys000
/Users/astudent/Desktop/mu ; exit;
bobcat-107-69:~ astudent$ /Users/astudent/Desktop/mu ; exit;

[14599] Error loading Python lib '/var/folders/tm/5nnwfzt121dgtqrw849lk76h0000gn/T/_MEIumg4Dl/Python': dlopen: dlopen(/var/folders/tm/5nnwfzt121dgtqrw849lk76h0000gn/T/_MEIumg4Dl/Python, 10): Symbol not found: _clock_getres
  Referenced from: /var/folders/tm/5nnwfzt121dgtqrw849lk76h0000gn/T/_MEIumg4Dl/Python (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /var/folders/tm/5nnwfzt121dgtqrw849lk76h0000gn/T/_MEIumg4Dl/Python
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
[Process completed]
```

My suspicion is that the symbol `_clock_getres` cannot be found, and that it looks like that the software was built on 10.12, that this is a case of "the student needs to update their OS" as an easy possible fix. I cannot say that this is a consistent error for all users of macOS 10.11. I can say that multiple students in the classroom experienced crashing bugs which I did not have eyes-on; my TAs did, and my impression was that the crashes were all the same. I only saw the error text after the period ended, because I was busy answering other questions.

So, that's the bug report. I'm happy to do my best to provide additional information/run under a debugger/etc. as necessary.

**Comment by ladyada** [comment]
hiya that's correct and a known issue
https://learn.adafruit.com/welcome-to-circuitpython/installing-mu-editor
"or Mac OS X you must be running 10.12 (Sierra) or higher (Mac users with lower versions can try the Linux instructions below, but YMMV)"

our first recommendation is to install from source
https://learn.adafruit.com/welcome-to-circuitpython/installing-mu-editor#installing-mu-for-linux
please try that!
