### ISSUE TITLE
1.0.0beta15   creates sounds/images folders

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/mu#2]
mu seems to be creating folders on my CIRCUITPY drive:
sounds - with eep.wav
images - with alien.png and alien_hurt.png

I also find a copy of these on my host machine in the mu_code folder.

Is this a bug or a "feature"?

**Comment by ladyada** [comment]
heya jerry - this is just our development fork, can you open an issue on https://github.com/mu-editor/mu ?
